### ISSUE TITLE
Error after clicking "Confirm Order"

### ISSUE THREAD

**Issue by Hammad51** [emreacar/Stripe-Payment-For-Opencart-3.x#1]
Publishable & Secret key set properly for test mode but still getting;
Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js

**Comment by emreacar** [comment]
Hi, Are you set your publishable key on admin panel ?

**Comment by Hammad51** [comment]
Yes

**Comment by emreacar** [comment]
Please confirm, your test publishable and secret api key correctly set. Sometimes users set secret key to publish key and publish key to secret key. Are you sure secret key to secret key are so publishable too.

If sure you set correctly; could you send me chrome dev tool console log after submitting error.

**Comment by Hammad51** [comment]
I double checked both key's, they are correct.
Admin panel is working fine.
Getting this error on checkout page after clicking "Confirm Order"
Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js

**Comment by mergenchik** [comment]
I got the same issue, in file  /upload/catalog/view/theme/default/template/extension/payment/stripe.twig on line 118 Stripe.setPublishableKey('{{publishable_key}}') always rendered as Stripe.setPublishableKey('') on opencart version 3.0.2.0

**Comment by Hammad51** [comment]
@mergenchik did you fixed the issue?

**Comment by emreacar** [comment]
In model and controller files when get configs, I had some bugs. I fixed this now. could you try again after install new files.
