### ISSUE TITLE
GBP Currency Missing

### ISSUE THREAD

**Issue by Webbo2018** [emreacar/Stripe-Payment-For-Opencart-3.x#11]
Please could you add GBP currency
Only has USD and EUR at the moment.

**Comment by emreacar** [comment]
@Webbo2018  You can add new currency options from Currency menu under opencart locally settings.

**Comment by Webbo2018** [comment]
Thank you Emre,

But it makes no difference to the Stripe Payment Gateway for Opencart 3 if GBP is set in opencart, GBP is not set on the extension, only USD and EUR

This Extension is still no use for UK

Kind Regards,
David

**Comment by emreacar** [comment]
Hi, yes you right. I'm sorry to forget this information. Stripe isn't allow checkout without euro or usd. So we can't do anything about that.

**Comment by Webbo2018** [comment]
Thank you Emre,

Please can you add GBP to the already USD and EUR, so you have the 3 options, instead of 2?

Kind regards,
David
