### ISSUE TITLE
Could not find payment information and page locked

### ISSUE THREAD

**Issue by michelevirgilio** [emreacar/Stripe-Payment-For-Opencart-3.x#12]
I've just installed the extension;
 when i proceed to checkout for a test order, leaving blank fields for credit card information and pushing the check out button, i get (rightly) a "Could not find payment information" error near the "Credit card details" field, but the button remains stuck on "loading..." and the page is semi-transparent, with no user interaction possible.
Any clue?
Thanks
http://testing103.oggiweb.com

**Comment by emreacar** [comment]
I'm sorry you are using one-page checkout extension for opencart. I don't think this about stripe payment module. Could you close one-page checkout extention and try again it ?

**Comment by michelevirgilio** [comment]
Ok, thank you, i've disabled the one-page checkout, but now i'm getting this error in both payment page and admin area (extensions > payments > stripe):

Fatal error: Uncaught Stripe\Error\ApiConnection: Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com. (Network error [errno 77]: error setting certificate verify locations: CAfile: <omitted>\upload\system\library\stripe-php\HttpClient/../../data/ca-certificates.crt CApath: none

**Comment by emreacar** [comment]
It's about your CA cert. permission. Could you read this page;

https://github.com/googleads/googleads-php-lib/issues/313
