### ISSUE TITLE
Undefined index: existingCard

### ISSUE THREAD

**Issue by wguerram** [emreacar/Stripe-Payment-For-Opencart-3.x#13]
Hello, when I click confirm order on the test environment I get the error Undefined index: existingCard in catalog/controller/extension/payment/stripe.php on line 53

What could be the cause to that issue?

**Comment by emreacar** [comment]
I think solution is here. Some reason on model/stripe.php install() method not fired some versions. If you can trigger metod problem will solve or try add tables manually;

https://github.com/emreacar/Stripe-Payment-For-Opencart-3.x/issues/6
