### ISSUE TITLE
Confirm Order error

### ISSUE THREAD

**Issue by wguerram** [emreacar/Stripe-Payment-For-Opencart-3.x#14]
I passed the error Undefined index: existingCard, after collapsing and expanding the paymet tab. Not fixed yet.

When I click confirm order I get:
index.php?route=extension/payment/stripe/send 500 (Internal Server Error)

If I look in Stripe Dashboard the data was received and send back successfully but the extension is not recognizing something and it just stay in the payment screen. It does not show an error or success message.

By looking at chrome tools I see

![stripe err](https://user-images.githubusercontent.com/8525985/44630073-7fe63200-a915-11e8-8100-1a157077e516.PNG)

By looking the logs I see (I'm doing guest checkout):

PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: Table 'db.oc_stripe_customer' doesn't exist<br />Error No: 1146<br />SELECT * FROM `oc_stripe_customer` WHERE `customer_id` = '' LIMIT 1' in /system/library/db/mysqli.php:40
Stack trace:
#0 /system/library/db.php(45): DB\MySQLi->query('SELECT * FROM `...')
#1 /catal

**Comment by wguerram** [comment]
I fixed the issue by creating the tables manually.

why the tables are not created when I install the extension?

**Comment by emreacar** [comment]
@wguerram When extention installing tables create automatically. Are you sure install ext. correctly ?

There is code in model folder ->install() method.

**Comment by trixlogix** [comment]
Manually adding the tables will resolve the issue.

CREATE TABLE IF NOT EXISTS oc_stripe_order (
			stripe_order_id varchar(255) NOT NULL,
			order_id int(11) NOT NULL DEFAULT "0",
			environment varchar(5) NOT NULL DEFAULT "test",
			PRIMARY KEY (stripe_order_id)
		) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_card (
			  stripe_card_id varchar(255) NOT NULL,
			  customer_id INT(11) NOT NULL,
			  last_four VARCHAR(4) NOT NULL,
			  exp_year VARCHAR(5) NOT NULL,
			  exp_month VARCHAR(5) NOT NULL,
			  brand VARCHAR(50) NOT NULL,
			  environment varchar(5) NOT NULL DEFAULT "test",
			  PRIMARY KEY (stripe_card_id)
			) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_customer (
			  customer_id INT(11) NOT NULL,
			  stripe_customer_id varchar(255) NOT NULL,
			  environment varchar(5) NOT NULL DEFAULT "test",
			  PRIMARY KEY (stripe_customer_id)
			) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci
