### ISSUE TITLE
Stripe in opencart 3.0.2 issue

### ISSUE THREAD

**Issue by devsujoy18** [emreacar/Stripe-Payment-For-Opencart-3.x#15]
After clicking confirm order it shows validating your credit card but nothing happened.Please help what is the exact problem?

https://mksupermart.work.smhosting.co.in

**Comment by lagartoi** [comment]
Solution: create this tables.
CREATE TABLE IF NOT EXISTS oc_stripe_order (
stripe_order_id varchar(255) NOT NULL,
order_id int(11) NOT NULL DEFAULT "0",
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_order_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_card (
stripe_card_id varchar(255) NOT NULL,
customer_id INT(11) NOT NULL,
last_four VARCHAR(4) NOT NULL,
exp_year VARCHAR(5) NOT NULL,
exp_month VARCHAR(5) NOT NULL,
brand VARCHAR(50) NOT NULL,
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_card_id)
) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_customer (
customer_id INT(11) NOT NULL,
stripe_customer_id varchar(255) NOT NULL,
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_customer_id)
) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci
