### ISSUE TITLE
Checking for nonexistent permission for install()/uninstall()

### ISSUE THREAD

**Issue by excsniper** [emreacar/Stripe-Payment-For-Opencart-3.x#5]
Hi, I'm trying to install the extension on OpenCart v3.0.2.0 but it looks like there's a check for the `extension/extension` permission before installing/uninstalling which doesn't exist on my version of OC. Please confirm if this permission is still valid. I've removed these checks as a temporary workaround in order to install the extension properly.
Thanks.

**Comment by emreacar** [comment]
You can enable permissions from OC MENU -> Settings -> User Groups -> Administrator after opened page, select all permission items and save. (Some version you must re-login oc as admin)
