### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by fletchersplace** [emreacar/Stripe-Payment-For-Opencart-3.x#6]
After hitting Cofirm Order. There is no redirect, no successful payment, declined, etc. notification. Live or in test mode.

**Comment by OzzyBloke** [comment]
Experiencing the same issue, v3.0.2.0, in test mode.  Tokens being received and accepted at Stripe.  Notice the returned response body all the address details are NULL and the currency is in USD where I am sending NZD.  No errors in OC, no errors at stripe.   Installed on a vanilla version of OC

**Comment by goldglamor** [comment]
Same Problem here - Press "Confirm Order' and nothing happens.  Stripe reports 200, so all good from that end - Live and Test. 

OC v3.0.2.0

**Comment by emreacar** [comment]
Please check browsers console (Dev tools). Is there any error from javascript or after hitting confirm button.

**Comment by lagartoi** [comment]
Same problem - Anyone found a solution or another module that work with Stripe.
Thanks

**Comment by lagartoi** [comment]
I found the solution only need to create this tables.
CREATE TABLE IF NOT EXISTS oc_stripe_order (
stripe_order_id varchar(255) NOT NULL,
order_id int(11) NOT NULL DEFAULT "0",
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_order_id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_card (
stripe_card_id varchar(255) NOT NULL,
customer_id INT(11) NOT NULL,
last_four VARCHAR(4) NOT NULL,
exp_year VARCHAR(5) NOT NULL,
exp_month VARCHAR(5) NOT NULL,
brand VARCHAR(50) NOT NULL,
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_card_id)
) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci

CREATE TABLE IF NOT EXISTS oc_stripe_customer (
customer_id INT(11) NOT NULL,
stripe_customer_id varchar(255) NOT NULL,
environment varchar(5) NOT NULL DEFAULT "test",
PRIMARY KEY (stripe_customer_id)
) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci

**Comment by emreacar** [comment]
model/stripe/install not fire from opencart extension installation. I don't know why but if you can create stripe databases manually problem solve. Thanks your answer @lagartoi
