### ISSUE TITLE
Issue with submitting order

### ISSUE THREAD

**Issue by mirkhan123** [emreacar/Stripe-Payment-For-Opencart-3.x#7]
Fatal Error how do i resolve this error , Uncaught Exception: Error: Table oc_stripe_customer' doesn't exist.  in opencart 3.x

**Comment by CoreSoft2** [comment]
Model is not initialized, if you have installed default db prefix, use this 


			
			
CREATE TABLE IF NOT EXISTS `oc_stripe_order` ( `stripe_order_id` varchar(255) NOT NULL,`order_id` int(11) NOT NULL DEFAULT '0',`environment` varchar(5) NOT NULL DEFAULT 'test', PRIMARY KEY (`stripe_order_id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `oc_stripe_card` ( `stripe_card_id` varchar(255) NOT NULL, `customer_id` INT(11) NOT NULL,  `last_four` VARCHAR(4) NOT NULL,  `exp_year` VARCHAR(5) NOT NULL,`exp_month` VARCHAR(5) NOT NULL,  `brand` VARCHAR(50) NOT NULL, `environment` varchar(5) NOT NULL DEFAULT 'test', PRIMARY KEY (`stripe_card_id`) ) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `oc_stripe_customer` (   `customer_id` INT(11) NOT NULL,  `stripe_customer_id` varchar(255) NOT NULL,  `environment` varchar(5) NOT NULL DEFAULT 'test',  PRIMARY KEY (`stripe_customer_id`) ) ENGINE=MyISAM DEFAULT COLLATE=utf8_general_ci;
